### ISSUE TITLE
Replace the backend with Strapi

### ISSUE THREAD

**Issue by lparolari** [ondanieldev/wellets-backend#3]
In the last two days I tried to add a feature to your project: mark a currency as favorite to let it shows first than others in the list.

I tried to implement this in order to get familiar with your code base because I have in mind to add some other features in the next future (mainly savings plan).

However, the implementation of this feature was a real pain. I mean, your code structure is very good and intuitive, but the technologies make many things harder than what they should be. 

So it comes in my mind an idea: replace the backend with [Strapi](https://strapi.io/), which is an awesome developer tool to build headless CSM. I used it some times ago with another project and I can confirm that is adaptable to many kind of jobs.

You can build "tables" in seconds and you can override default behavior with plain JavaScript (or TypeScript) code for more complex operations. You can create very complex data structure, starting from simple textual fields up to relations and dynamic fields. You can manage collections and single types through their management panel (which generates code based on what you change) or directly with your editor writing code. It's deployment is git-based and can be easily managed by free service like heroku (don't know about Vercel, the one you are using, but should be).

Also, it exposes all data through GraphQL which is mentioned in your roadmap.

What do you think?

**Comment by ondanieldev** [comment]
Hey, sorry, I'm late to answer that!
I was thinking about your proposal and researching Strapi. Well, I don't want to make heavy changes to the structure of the code, mainly because I don't have much time to replace everything and because it's a pattern that I'm very familiar with. In fact, it is very easy to develop under this pattern, but it can be a bit difficult for those who are not familiar.
However, if you want, we can make a video conference so I can explain all about it to you and resolve your questions.
I think your pain is dealing with TypeORM. I agree that he has his problems, but it is very easy to develop with him when you are accustomed.

**Comment by lparolari** [comment]
Yeah, you are completely right. 

In fact, I never used those technologies and I may have had a technical debt. However, after some headaches mainly with TypeORM I started appreciating it and the pattern you followed.

About last point, what is the name of the main pattern you followed? I will give it a look in order to study it for writing better code. The structure seems very similar to a NextJS project but yours seems vanilla TypeScript code.

Also, let me know if you appreciate the features I'm adding to your project: I'm happy to contribute but only if you agree! 

Thank you for your time.
